services:
  - type: web
    name: gravityheist
    env: node
    buildCommand: yarn install
    startCommand: node server.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
